# Generated by Django 5.0.3 on 2024-03-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='categories_name_98d7d5_idx',
            old_name='shop_catego_name_289c7e_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_id_b7370b_idx',
            old_name='shop_produc_id_f21274_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_name_6f9890_idx',
            old_name='shop_produc_name_a2070e_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_created_63110b_idx',
            old_name='shop_produc_created_ef211c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'name')},
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
